import { spawn, ChildProcess } from 'child_process';
import { workspace, window } from 'vscode';

export function generateSolutionFiles() {
    const workspaceFolder = workspace.workspaceFolders?.[0];

    if (workspaceFolder) {
        // Path to the C++ file.
        const cppFilePath = window.activeTextEditor?.document.fileName;

        if (!cppFilePath) {
            window.showErrorMessage('No C++ file is currently open.');
            return;
        }

        // Path to the C++ project's .vcxproj file.
        // This is the file that will be generated by MSBuild.
        const vcxprojFilePath = workspaceFolder.uri.fsPath + '/MyCppProject.vcxproj';

        // Generate the .sln and .vcxproj files from the .cpp file.
        const msbuildProcess = spawn('msbuild', [cppFilePath, '/t:Build', '/p:Configuration=Debug', '/p:Platform=x64', '/p:VisualStudioVersion=16.0', '/p:VCTargetsPath=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\Microsoft\\VC\\v160\\']) as ChildProcess;

        // Handle the MSBuild process exit code.
        msbuildProcess.on('close', (code) => {
            if (code === 0) {
                window.showInformationMessage('C++ solution files generated successfully.');
            } else {
                window.showErrorMessage('Failed to generate C++ solution files.');
            }
        });
    }
}
